# Generated by Django 4.2.6 on 2023-11-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_notification_is_read_alter_notification_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='password',
        ),
    ]
