# Generated by Django 4.2.6 on 2023-11-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_myusermodel_notification_jobseeker_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='username',
        ),
    ]
