# Generated by Django 4.2.6 on 2023-11-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='auto_generated_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='auto_generated_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
