# Generated by Django 4.2.6 on 2023-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_auto_generated_password_jobseekerprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
