# Generated by Django 4.2.6 on 2023-11-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_employernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.job'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
