# Generated by Django 4.2.6 on 2023-11-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_notification_jobs_notification_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employer',
            new_name='employer_profile',
        ),
    ]
