# Generated by Django 4.2.6 on 2023-11-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
    ]
