# Generated by Django 4.2.6 on 2023-11-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_jobseekernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekernotification',
            name='notification_type',
            field=models.CharField(choices=[('selected', 'Selected Job'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
