# Generated by Django 4.2.6 on 2023-11-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_selectedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employernotification',
            name='notification_type',
            field=models.CharField(choices=[('applied', 'Applied Job'), ('selected', 'Selected Applicant')], max_length=50, null=True),
        ),
    ]
