# Generated by Django 4.2.6 on 2023-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_employernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employernotification',
            name='notification_type',
            field=models.CharField(choices=[('applied', 'Applied Job'), ('selected', 'Selected Job')], max_length=50, null=True),
        ),
    ]
