# Generated by Django 4.2.6 on 2023-12-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_verifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20, null=True),
        ),
    ]
