# Generated by Django 4.2.6 on 2023-12-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full Time'), ('Part time', 'Part Time')], max_length=20, null=True),
        ),
    ]
