# Generated by Django 4.2.6 on 2024-01-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_employernotification_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
